service: grafico-seguimiento-invrtir

provider:
  name: aws
  runtime: nodejs14.x
  stage: seg
  region: us-east-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'